apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config-helm-chart-value-overrides
  namespace: metallb-config
data:
  values.yaml: |-  
    image:
      repository: hello-world
      tag: latest@sha256:53cc4d415d839c98be39331c948609b659ed725170ad2ca8eb36951288f81b75
      pullPolicy: IfNotPresent
    manifestManager:
      enabled: false
    workload:
      main:
        enabled: false
        podSpec:
          containers:
            main:
              enabled: false
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
    service:
      main:
        enabled: false
        ports:
          main:
            enabled: false
            port: 9999
    operator:
      metallb:
        namespace: metallb-system
    portal:
      open:
        enabled: false
    ipAddressPools:
       - name: metallb-pool
         autoAssign: true
         avoidBuggyIPs: true
         addresses:
           - 192.168.50.0/24
    L2Advertisements: []
    #   - name: l2adv
    #     addressPools:
    #       - pool1
    #     nodeSelectors:
    #       - nodeA
    BGPAdvertisements:
       - name: metallb-advertisment
         addressPools:
           - metallb-pool
    #     aggregationLength: 24
    #     localpref: 100
    #     communities:
    #       - 1234:1
    #     peers:
    #       - peer1
    Communities: []
    #   - name: community1
    #     value: 1234:1
    Peers:
       - name: bgppeer-192.168.20.1
         myASN: 64512
         peerASN: 64512
    #     password: pass
    #     routerID: 1234
    #     bfdProfile: profile
    #     ebgpMultiHop: false
         holdTime: 1m30s
         keepaliveTime: 0
         peerAddress: 192.168.20.1
    #     peerPort: 179
    #     sourceAddress: 172.30.0.3
    #     nodeSelectors:
    #       - nodeA
