apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  chart:
    spec:
      chart: clusterissuer
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: clusterissuer
  valuesFrom:
  - kind: ConfigMap
    name: clusterissuer-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
