apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb-config
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: metallb
  valuesFrom:
  - kind: ConfigMap
    name: metallb-config-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
