apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: truenas-nfs-storage
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: v4.0.x
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nfs-subdir-external-provisioner
  valuesFrom:
  - kind: ConfigMap
    name: nfs-subdir-external-provisioner-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
