apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: csi-driver-nfs
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: csi-driver-nfs-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
