apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
spec:
  chart:
    spec:
      chart: prometheus-operator
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: prometheus-operator
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
        retries: 3
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-operator-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
