apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: kube-system
spec:
  chart:
    spec:
      chart: treafik-crds
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: traefik-crds
  valuesFrom:
  - kind: ConfigMap
    name: traefik-crds-helm-chart-value-overrides
    namespace: kube-system
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
